// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index(errorMsg string, role string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html><head><title>Car Dealership</title><link rel=\"stylesheet\" href=\"assets/styles/login.css\"></head><body><div class=\"login-container\"><div class=\"login-form\"><p>Welcome, please login or continue as guest</p><span id=\"error-message\" style=\"color: red; font-weight: bold; display: none;\">Invalid credentials</span><form action=\"/login\" method=\"POST\"><label for=\"email\">Email:</label> <input type=\"email\" id=\"email\" name=\"email\" required> <label for=\"password\">Password:</label> <input type=\"password\" id=\"password\" name=\"password\" required> <button type=\"submit\">Log in</button></form></div><a href=\"#\" class=\"guest-button\" onclick=\"continueAsGuest()\">Continue as Guest</a></div><script>\n        const urlParams = new URLSearchParams(window.location.search);\n        if (urlParams.get('error') === 'invalid_user') {\n            document.getElementById('error-message').style.display = 'block';\n        }\n\n        function continueAsGuest() {\n        document.cookie = \"user_role=0; path=/\";\n        document.cookie = \"user_name=Guest; path=/\";\n\n        window.location.href = \"/store\";\n    }\n    </script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
